{% set version = "2.0.2" %}
{% set build_num = "1" %}
{% set sha256 = "afb472f0b032a5e503c07fcb0b276a9c664885ad428185de70619cc607dbd735" %}

package:
  name: gpi_core
  version: {{ version }}

source:
  url: https://github.com/gpilab/core-nodes/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  folder: repo_contents

build:
  number: {{ build_num }}
  detect_binary_files_with_prefix: True
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}  
    - {{ compiler('cxx') }}
  host:
    - cytoolz
    - gpi >=1.1.5
    - numpy =1.11
    - python
  run:
    - {{ pin_compatible('gpi') }}
    - matplotlib >=2.1,<3
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  imports:
    - gpi
    - gpi_core
  source_files:
    - repo_contents/testNets/*

about:
  home: http://gpilab.com
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Core nodes for the GPI development framework"
  description: |
    These nodes provide basic functionality for GPI, such as mathematical
    operations, data shape modifiers, and data generators. Some basic
    tools for spiral MRI reconstruction are also included.
  dev_url: https://github.com/gpilab/core-nodes

extra:
  recipe-maintainers:
    - borupdaniel
    - aganders3
