{% set version = "2.3.1" %}

package:
  name: gpi_core
  version: {{ version }}

source:
  url: https://github.com/gpilab/core-nodes/archive/v{{ version }}.tar.gz
  sha256: 180609fe0e82d9b55abb82a2b2355130e1961eaf55977598a3add79b94e163ed
  folder: repo_contents

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [py2k]
  skip: true  # [osx and py<=36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cytoolz
    - gpi >=1.2.0  # [not win]
    - gpi >=1.2.6  # [win]
    - numpy =1.14  # [py==38]
    - numpy =1.11  # [py<38]
    - pthreads-win32  # [win]
    - python
  run:
    - {{ pin_compatible('gpi') }}
    - matplotlib-base >=2.1,<3.3  # [not osx or py>=38]
    - matplotlib-base >=2.1,<3.1.1  # [osx and py<=37]
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pthreads-win32') }}  # [win]
    - pydicom
    - python
    - scipy

test:
  requires:
    - xorg-libsm  # [linux]
    - xorg-libxcb  # [linux]
    - xorg-libxrender  # [linux]
  imports:
    - gpi
    - gpi_core
  files:
    - TestNetwork.net

about:
  home: http://gpilab.com
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Core nodes for the GPI development framework
  description: |
    These nodes provide basic functionality for GPI, such as mathematical
    operations, data shape modifiers, and data generators. Some basic
    tools for spiral MRI reconstruction are also included.
  dev_url: https://github.com/gpilab/core-nodes

extra:
  recipe-maintainers:
    - borupdaniel
    - aganders3
    - aboudfayad
