{% set version = "2.2.0" %}

package:
  name: gpi_core
  version: {{ version }}

source:
  url: https://github.com/gpilab/core-nodes/archive/v{{ version }}.tar.gz
  sha256: db568aca4d66a337f6f9f561aec097631d6d04661d1f6eb9babfa667daaaa81e
  folder: repo_contents

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cytoolz
    - gpi >=1.2.0  # [not win]
    - gpi >=1.2.6  # [win]
    - numpy =1.14  # [py==38]
    - numpy =1.11  # [py<38]
    - pthreads-win32  # [win]
    - python
    - pydicom
  run:
    - {{ pin_compatible('gpi') }}
    - matplotlib-base >=2.1,<3.3
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pthreads-win32') }}  # [win]
    - python
    - scipy

test:
  requires:
    - xorg-libsm  # [linux]
    - xorg-libxcb  # [linux]
    - xorg-libxrender  # [linux]
  imports:
    - gpi
    - gpi_core
  files:
    - TestNetwork.net

about:
  home: http://gpilab.com
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Core nodes for the GPI development framework
  description: |
    These nodes provide basic functionality for GPI, such as mathematical
    operations, data shape modifiers, and data generators. Some basic
    tools for spiral MRI reconstruction are also included.
  dev_url: https://github.com/gpilab/core-nodes

extra:
  recipe-maintainers:
    - borupdaniel
    - aganders3
